application: sykes-locations
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon/favicon.ico
  upload: favicon/(.*\.ico)
- url: /favicon/(.*\.(png|xml|ico|json|svg))
  static_files: favicon/\1
  upload: favicon/(.*\.(png|xml|ico|json|svg))
- url: /master
  script: main.bottle
  login: admin
  secure: always
- url: .*
  script: main.bottle
  secure: always

skip_files:
# defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# prevent default theme from overriding mine
- ^(bower_components/paper-styles/default-theme.html)$
